name: 'C# Project Version Reader'
description: 'Reads the version of a C#'
author: 'yaos ltd'
inputs: 
  FilePath:
    description: 'Path to project file'
    required: true
outputs:
  Version
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.FilePath }}
